# Generated by Django 5.2.11 on 2026-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_o_id', models.ManyToManyField(related_name='player_o_game', to='tictactoe.user')),
                ('player_x_id', models.ManyToManyField(related_name='player_x_game', to='tictactoe.user')),
            ],
        ),
    ]
