# Generated by Django 5.2.11 on 2026-02-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_o_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_x_id',
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='current_board',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mini_board_winners',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='next_board',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='player_o',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_o_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player_x',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_x_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
